FROM php:8.2-fpm

RUN apt-get update && apt-get install -y git unzip \
    && docker-php-ext-install pdo pdo_mysql \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /usr/share/nginx/html